from django.urls import path
from AdminApp import views
urlpatterns = [
    path('login/', views.Login, name="login"),
    path('signup/', views.Signup, name="signup"),
    path('student_dashboard/', views.Student_Dashboard, name="student"),
    path('teacher_dashboard/', views.Teacher_Dashboard, name="teacher"),
    path('admin_dashboard/', views.Admin_Dashboard, name="admin"),
    path('change_password/', views.Change_Password, name="change_password"),
    path('logout/', views.Logout, name="logout"),
    path('addsub/', views.Add_Subject, name="addsub"),
    path('blogpost/', views.Blog_Posting, name="blogpost"),
    path('blogshow/', views.Blog_show, name="blogshow"),
    path('request_view/', views.Request_View, name="request_view"),
    path('manage_view/', views.Manage_View, name="manage_view"),
    path('start_course/<int:id>/', views.Course_content, name="course_content"),
    path('start_course/<int:id>/newsection',
         views.New_section, name="new_Section"),
    path('del_section/<int:id>', views.Del_section, name="del_Section"),
    path('manage_upload/', views.Manage_upload, name="manage_upload"),
    path('teacher_request/', views.Teacher_Requset_View, name="teacher_request"),
    path('profile_pic/', views.Profile_pic, name="profile_pic"),
    path('student_course/', views.Student_Course, name="student_course"),
    path('add_doubt/', views.Doubt_Post, name="add_doubt"),
    path('doubt_show/', views.Show_doubt, name="doubt_show"),
    path('edit_doubt/<int:id>/', views.Edit_doubt, name="edit_doubt"),
    path('delete_doubt/<int:id>/', views.Delete_doubt, name="delete_doubt"),
    path('note/', views.Note, name="note"),
    path('add_note/', views.Add_note, name="add_note"),
    path('edit_note/<int:id>/', views.Edit_note, name="edit_note"),
    path('delete_note/<int:id>/', views.Delete_note, name="delete_note"),
    path('user_profile/', views.User_Profile, name="user_profile"),
    path('techer_rqst/', views.Teacher_rqst, name="techer_rqst"),
    path('forgotpassword/', views.ForgotPassword, name='forgotpassword'),
    path('verifyuser/', views.VerifyUser, name='verifyuser'),
    path('certificate/<int:id>/<int:tid>/',
         views.Gen_Cert, name='certificate'),
    path('add_to_account/<int:id>/<int:tid>/',
         views.Add_To_Acc, name='add_to_account'),
    path('delete_course/<int:id>/', views.Delete_Course, name='delete_course'),
    path('edit_course/<int:id>/', views.Edit_Course, name='edit_course'),
    path('accept_teacher/<int:id>/', views.Accept_Teacher, name='accept_teacher'),
    path('reject_teacher/<int:id>/', views.Reject_Teacher, name='reject_teacher'),
]
