# Generated by Django 3.0.8 on 2021-03-15 16:52

import AdminApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('post_user', models.CharField(max_length=255, null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.FileField(blank=True, default=False, upload_to='blog_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=255, null=True)),
                ('cabout', models.TextField(blank=True, max_length=1000, null=True)),
                ('cimage', models.FileField(blank=True, default=False, upload_to='courseimages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Request',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('approve', 'approve'), ('rejected', 'rejected'), ('pending', 'pending'), ('notsent', 'notsent')], default='notsent', max_length=30)),
                ('skills', models.CharField(blank=True, max_length=1000, null=True)),
                ('gcertificate', models.FileField(blank=True, null=True, upload_to=AdminApp.models.user_directory_path)),
                ('twocertificate', models.FileField(blank=True, null=True, upload_to=AdminApp.models.user_directory_path)),
                ('tencertificate', models.FileField(blank=True, null=True, upload_to=AdminApp.models.user_directory_path)),
                ('resume', models.FileField(blank=True, null=True, upload_to=AdminApp.models.user_directory_path)),
                ('demovideo', models.FileField(blank=True, null=True, upload_to=AdminApp.models.user_directory_path)),
                ('why_teacher', models.CharField(blank=True, max_length=1000, null=True)),
                ('experience', models.CharField(blank=True, max_length=1000, null=True)),
                ('accomplishments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('dob', models.CharField(max_length=50, null=True)),
                ('usertype', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('admin', 'admin')], default='student', max_length=10)),
                ('Profile_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('allow', 'allow'), ('deny', 'deny'), ('pending', 'pending'), ('notsent', 'notsent')], default='notsent', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Take_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete')], default='incomplete', max_length=30)),
                ('certificate', models.FileField(blank=True, default=False, upload_to='certificate')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('teacher_id', models.CharField(max_length=250, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('doubt', models.TextField(null=True)),
                ('postby', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('answerby', models.CharField(max_length=255, null=True)),
                ('ans', models.TextField()),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.Doubt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
