# Generated by Django 3.1.7 on 2021-04-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_auto_20210405_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='cabout',
        ),
    ]
